/**
 * Interaction system — proximity detection, pickup, drop, examine, and push/drag.
 *
 * Runs each fixed tick after InputSystem. Detects interactable objects within
 * range of the player, handles E-key interactions, and processes pointer-based
 * drag/push for immovable objects.
 *
 * NO React imports — this is pure game-side TypeScript.
 */

import type { SceneContext } from "./scene-context";
import type { SystemFn } from "./system-runner";
import type { Entity } from "@/game/ecs/entity";
import { world } from "@/game/ecs/world";
import {
  interactableEntities,
  inventoryEntities,
} from "@/game/ecs/queries";
import { createObjectEntity } from "@/game/ecs/archetypes";
import { getObjectDef } from "@/game/procgen/object-defs";
import { safeEmit } from "@/game/events/event-bus";
import type { InventorySlot } from "@/game/events/event-bus";

// ---------------------------------------------------------------------------
// Tuning constants
// ---------------------------------------------------------------------------

/** Maximum distance (pixels) for interaction prompts to appear. */
export const INTERACTION_RANGE = 48;

/** Force magnitude (Newtons) applied per tick when dragging an object. */
export const DRAG_FORCE = 0.005;

/** Noise radius (pixels) generated by dragging objects. */
export const DRAG_NOISE_RADIUS = 200;

/**
 * Maximum carry weight penalty — at maxCarryWeight the player moves
 * at this fraction of normal speed.
 */
export const MIN_SPEED_MULTIPLIER = 0.4;

/** Offset (pixels) in front of the player to drop items. */
export const DROP_OFFSET = 40;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Squared Euclidean distance between two 2D points. */
function distSq(ax: number, ay: number, bx: number, by: number): number {
  const dx = ax - bx;
  const dy = ay - by;
  return dx * dx + dy * dy;
}

/**
 * Compute a speed multiplier [MIN_SPEED_MULTIPLIER, 1.0] based on
 * carry weight as a fraction of max capacity.
 */
export function computeSpeedMultiplier(
  carryWeight: number,
  maxCarryWeight: number,
): number {
  if (maxCarryWeight <= 0) return 1;
  const fraction = Math.min(carryWeight / maxCarryWeight, 1);
  return 1 - fraction * (1 - MIN_SPEED_MULTIPLIER);
}

/**
 * Build an InventorySlot array from the inventory items for the
 * inventory-changed event.
 */
function buildSlots(
  items: Array<{ objectType: string; quantity: number }>,
): InventorySlot[] {
  return items.map((item, i) => ({
    itemType: item.objectType,
    quantity: item.quantity,
    slotIndex: i,
  }));
}

// ---------------------------------------------------------------------------
// System factory
// ---------------------------------------------------------------------------

/**
 * Create the interaction system.
 *
 * The system handles:
 * 1. Proximity detection — highlights nearest interactable, emits prompts
 * 2. E-key pickup — removes entity, adds to inventory, emits events
 * 3. E-key examine — for immovable objects, emits details
 * 4. Pointer drag/push — applies force to immovable objects
 * 5. Drop commands — spawns entity from inventory at player position
 */
export function createInteractionSystem(ctx: SceneContext): SystemFn {
  const rangeSq = INTERACTION_RANGE * INTERACTION_RANGE;

  /** The entity currently highlighted (for prompt tracking). */
  let promptedEntity: Entity | null = null;

  // Buffer drop commands from UI
  const pendingDrops: string[] = [];

  ctx.eventBus.on("cmd:drop-item", (e) => {
    pendingDrops.push(e.objectType);
  });

  return (_dt: number): void => {
    // Use inventoryEntities query — guarantees playerControlled + position + inventory
    const player = inventoryEntities.entities[0];
    if (!player) return;

    const px = player.position.x;
    const py = player.position.y;
    const inv = player.inventory;

    // --- 1. Proximity detection & highlighting ---

    let nearestEntity: Entity | null = null;
    let nearestDistSq = Infinity;

    for (const entity of interactableEntities) {
      const d = distSq(px, py, entity.position.x, entity.position.y);
      if (d <= rangeSq && d < nearestDistSq) {
        nearestDistSq = d;
        nearestEntity = entity;
      }
      // Clear any previous highlight
      entity.interactable.highlighted = false;
    }

    if (nearestEntity) {
      nearestEntity.interactable!.highlighted = true;

      // Emit prompt if it's a new entity or first time
      if (nearestEntity !== promptedEntity) {
        const op = nearestEntity.objectProperties!;
        const def = getObjectDef(op.objectType);
        safeEmit(ctx.eventBus, "interaction-prompt", {
          objectType: op.objectType,
          displayName: def?.displayName ?? op.objectType,
          interactionType: nearestEntity.interactable!.interactionType,
          immovable: op.immovable,
          worldX: nearestEntity.position!.x,
          worldY: nearestEntity.position!.y,
        });
        promptedEntity = nearestEntity;
      }
    } else if (promptedEntity !== null) {
      safeEmit(ctx.eventBus, "interaction-prompt-clear", {});
      promptedEntity = null;
    }

    // --- 2. E-key interactions ---

    if (ctx.inputState.interactPressed && nearestEntity) {
      const op = nearestEntity.objectProperties!;
      const inter = nearestEntity.interactable!;

      if (!op.immovable && inter.interactionType === "pickup") {
        // --- Pickup ---
        const def = getObjectDef(op.objectType);
        const mass = def?.physics.mass ?? 1;

        // Add to inventory
        const existing = inv.items.find(
          (i) => i.objectType === op.objectType,
        );
        if (existing) {
          existing.quantity += 1;
        } else {
          inv.items.push({ objectType: op.objectType, quantity: 1 });
        }
        inv.carryWeight += mass;

        // Remove from world — ECS + physics registry + Matter body
        const bodyId = nearestEntity.physicsBody?.bodyId;
        if (bodyId !== undefined) {
          const body = ctx.bodyRegistry.get(bodyId);
          if (body) {
            ctx.scene.matter.world.remove(body);
          }
          ctx.bodyRegistry.unregister(bodyId);
        }
        world.remove(nearestEntity);

        // Emit events
        safeEmit(ctx.eventBus, "item-picked-up", {
          itemType: op.objectType,
          quantity: 1,
        });
        safeEmit(ctx.eventBus, "inventory-changed", {
          slots: buildSlots(inv.items),
          carryWeight: inv.carryWeight,
          maxCarryWeight: inv.maxCarryWeight,
        });

        // Clear prompt since entity is gone
        safeEmit(ctx.eventBus, "interaction-prompt-clear", {});
        promptedEntity = null;
      } else {
        // --- Examine (for immovable or non-pickup objects) ---
        const def = getObjectDef(op.objectType);
        safeEmit(ctx.eventBus, "object-examined", {
          objectType: op.objectType,
          displayName: def?.displayName ?? op.objectType,
          category: op.category,
          properties: {
            durability: op.durability,
            flammability: op.flammability,
            conductivity: op.conductivity,
            lootValue: op.lootValue,
            immovable: op.immovable,
          },
        });
      }
    }

    // --- 3. Drag / push for immovable objects ---

    if (ctx.inputState.pointerDown && nearestEntity) {
      const op = nearestEntity.objectProperties!;
      if (op.immovable && nearestEntity.physicsBody) {
        const body = ctx.bodyRegistry.get(
          nearestEntity.physicsBody.bodyId,
        );
        if (body) {
          // Compute force direction from object toward pointer
          const objX = nearestEntity.position!.x;
          const objY = nearestEntity.position!.y;
          const dx = ctx.inputState.pointerWorldX - objX;
          const dy = ctx.inputState.pointerWorldY - objY;
          const dist = Math.sqrt(dx * dx + dy * dy);

          if (dist > 1) {
            const nx = dx / dist;
            const ny = dy / dist;

            // Apply force via Matter.js body
            body.force.x += nx * DRAG_FORCE;
            body.force.y += ny * DRAG_FORCE;

            // Emit noise for future zombie AI
            safeEmit(ctx.eventBus, "noise-generated", {
              position: { x: objX, y: objY },
              radius: DRAG_NOISE_RADIUS,
              source: "drag",
            });
          }
        }
      }
    }

    // --- 4. Drop commands from UI ---

    while (pendingDrops.length > 0) {
      const objectType = pendingDrops.pop()!;
      const itemIndex = inv.items.findIndex(
        (i) => i.objectType === objectType,
      );
      if (itemIndex === -1) continue;

      const def = getObjectDef(objectType);
      if (!def) continue;

      const mass = def.physics.mass;

      // Reduce inventory
      const item = inv.items[itemIndex];
      item.quantity -= 1;
      if (item.quantity <= 0) {
        inv.items.splice(itemIndex, 1);
      }
      inv.carryWeight = Math.max(0, inv.carryWeight - mass);

      // Compute drop position in front of player (based on aim direction)
      const aimDx = ctx.inputState.aimX - px;
      const aimDy = ctx.inputState.aimY - py;
      const aimDist = Math.sqrt(aimDx * aimDx + aimDy * aimDy);
      let dropX = px;
      let dropY = py + DROP_OFFSET;
      if (aimDist > 1) {
        dropX = px + (aimDx / aimDist) * DROP_OFFSET;
        dropY = py + (aimDy / aimDist) * DROP_OFFSET;
      }

      // Create physics body for dropped object
      const bodySize = def.immovable ? 32 : 16;
      const newBody = ctx.scene.matter.add.rectangle(
        dropX,
        dropY,
        bodySize,
        bodySize,
        {
          isStatic: def.immovable,
          friction: 0.8,
          frictionAir: 0.1,
          restitution: 0.2,
        },
      );
      newBody.inertia = Infinity;
      newBody.inverseInertia = 0;
      ctx.bodyRegistry.register(newBody);

      // Spawn ECS entity
      createObjectEntity(
        dropX,
        dropY,
        newBody.id,
        objectType,
        def.category,
        def.immovable,
        def.physics,
        def.lootValue,
      );

      // Emit events
      safeEmit(ctx.eventBus, "object-dropped", {
        objectType,
        position: { x: dropX, y: dropY },
      });
      safeEmit(ctx.eventBus, "inventory-changed", {
        slots: buildSlots(inv.items),
        carryWeight: inv.carryWeight,
        maxCarryWeight: inv.maxCarryWeight,
      });
    }
  };
}
