/**
 * Interaction system — proximity detection, pickup, drop, examine, and push/drag.
 *
 * Runs each fixed tick after InputSystem. Detects interactable objects within
 * range of the player, handles E-key interactions, and processes pointer-based
 * drag/push for immovable objects.
 *
 * NO React imports — this is pure game-side TypeScript.
 */

import type { SceneContext } from "./scene-context";
import type { SystemFn } from "./system-runner";
import type { Entity } from "@/game/ecs/entity";
import { world } from "@/game/ecs/world";
import {
  interactableEntities,
  inventoryEntities,
} from "@/game/ecs/queries";
import { createObjectEntity } from "@/game/ecs/archetypes";
import { getObjectDef } from "@/game/procgen/object-defs";
import { safeEmit } from "@/game/events/event-bus";
import {
  canAddItem,
  addItem,
  removeItem,
  removeItemByType,
  buildEventSlots,
} from "./inventory-utils";

// ---------------------------------------------------------------------------
// Tuning constants
// ---------------------------------------------------------------------------

/** Maximum distance (pixels) for interaction prompts to appear. */
export const INTERACTION_RANGE = 48;

/** Force magnitude (Newtons) applied per tick when dragging an object. */
export const DRAG_FORCE = 0.005;

/** Noise radius (pixels) generated by dragging objects. */
export const DRAG_NOISE_RADIUS = 200;

/**
 * Maximum carry weight penalty — at maxCarryWeight the player moves
 * at this fraction of normal speed.
 */
export const MIN_SPEED_MULTIPLIER = 0.4;

/** Offset (pixels) in front of the player to drop items. */
export const DROP_OFFSET = 40;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Squared Euclidean distance between two 2D points. */
function distSq(ax: number, ay: number, bx: number, by: number): number {
  const dx = ax - bx;
  const dy = ay - by;
  return dx * dx + dy * dy;
}

/**
 * Compute a speed multiplier [MIN_SPEED_MULTIPLIER, 1.0] based on
 * carry weight as a fraction of max capacity.
 */
export function computeSpeedMultiplier(
  carryWeight: number,
  maxCarryWeight: number,
): number {
  if (maxCarryWeight <= 0) return 1;
  const fraction = Math.min(carryWeight / maxCarryWeight, 1);
  return 1 - fraction * (1 - MIN_SPEED_MULTIPLIER);
}

// ---------------------------------------------------------------------------
// System factory
// ---------------------------------------------------------------------------

/**
 * Create the interaction system.
 *
 * The system handles:
 * 1. Proximity detection — highlights nearest interactable, emits prompts
 * 2. E-key pickup — removes entity, adds to inventory, emits events
 * 3. E-key examine — for immovable objects, emits details
 * 4. Pointer drag/push — applies force to immovable objects
 * 5. Drop commands — spawns entity from inventory at player position
 */
export function createInteractionSystem(ctx: SceneContext): SystemFn {
  const rangeSq = INTERACTION_RANGE * INTERACTION_RANGE;

  /** The entity currently highlighted (for prompt tracking). */
  let promptedEntity: Entity | null = null;

  // Buffer drop commands from UI
  const pendingDrops: Array<{ objectType?: string; slotIndex?: number }> = [];

  ctx.eventBus.on("cmd:drop-item", (e) => {
    pendingDrops.push({ objectType: e.objectType, slotIndex: e.slotIndex });
  });

  return (_dt: number): void => {
    // Use inventoryEntities query — guarantees playerControlled + position + inventory
    const player = inventoryEntities.entities[0];
    if (!player) return;

    const px = player.position.x;
    const py = player.position.y;
    const inv = player.inventory;

    // --- 1. Proximity detection & highlighting ---

    let nearestEntity: Entity | null = null;
    let nearestDistSq = Infinity;

    for (const entity of interactableEntities) {
      const d = distSq(px, py, entity.position.x, entity.position.y);
      if (d <= rangeSq && d < nearestDistSq) {
        nearestDistSq = d;
        nearestEntity = entity;
      }
      // Clear any previous highlight
      entity.interactable.highlighted = false;
    }

    if (nearestEntity) {
      nearestEntity.interactable!.highlighted = true;

      // Emit prompt if it's a new entity or first time
      if (nearestEntity !== promptedEntity) {
        const op = nearestEntity.objectProperties!;
        const def = getObjectDef(op.objectType);
        safeEmit(ctx.eventBus, "interaction-prompt", {
          objectType: op.objectType,
          displayName: def?.displayName ?? op.objectType,
          interactionType: nearestEntity.interactable!.interactionType,
          immovable: op.immovable,
          worldX: nearestEntity.position!.x,
          worldY: nearestEntity.position!.y,
        });
        promptedEntity = nearestEntity;
      }
    } else if (promptedEntity !== null) {
      safeEmit(ctx.eventBus, "interaction-prompt-clear", {});
      promptedEntity = null;
    }

    // --- 2. E-key interactions ---

    if (ctx.inputState.interactPressed && nearestEntity) {
      const op = nearestEntity.objectProperties!;
      const inter = nearestEntity.interactable!;

      if (!op.immovable && inter.interactionType === "pickup") {
        // --- Pickup ---
        const objectType = op.objectType;
        const def = getObjectDef(objectType);

        // Check slot availability before attempting world removal
        if (!canAddItem(inv, objectType)) {
          const displayName = def?.displayName ?? objectType;
          safeEmit(ctx.eventBus, "inventory-full", {
            attemptedItemType: objectType,
            displayName,
          });
        } else {
          // Remove from world FIRST (fail-fast before mutating inventory).
          // If removal throws, inventory stays untouched — no item duplication.
          let pickupSucceeded = false;

          try {
            const bodyId = nearestEntity.physicsBody?.bodyId;
            if (bodyId !== undefined) {
              const body = ctx.bodyRegistry.get(bodyId);
              if (body) {
                ctx.scene.matter.world.remove(body);
              }
              ctx.bodyRegistry.unregister(bodyId);
            }
            world.remove(nearestEntity);
            pickupSucceeded = true;
          } catch (err) {
            console.error(
              `[InteractionSystem] Pickup failed for ${objectType}:`,
              err,
            );
          }

          // Prevent stale reference in drag/drop sections below
          nearestEntity = null;

          if (pickupSucceeded) {
            // Add to inventory slot(s) — addItem handles weight update.
            // canAddItem was checked before world removal, so this should
            // succeed. Guard against edge cases defensively.
            const added = addItem(inv, objectType);
            if (added) {
              safeEmit(ctx.eventBus, "item-picked-up", {
                itemType: objectType,
                quantity: 1,
              });
              safeEmit(ctx.eventBus, "inventory-changed", {
                slots: buildEventSlots(inv),
                carryWeight: inv.carryWeight,
                maxCarryWeight: inv.maxCarryWeight,
              });
            } else {
              console.error(
                `[InteractionSystem] addItem failed after world removal for ${objectType}`,
              );
            }

            // Clear prompt regardless — entity was removed from world
            safeEmit(ctx.eventBus, "interaction-prompt-clear", {});
            promptedEntity = null;
          }
        }
      } else {
        // --- Examine (for immovable or non-pickup objects) ---
        const def = getObjectDef(op.objectType);
        safeEmit(ctx.eventBus, "object-examined", {
          objectType: op.objectType,
          displayName: def?.displayName ?? op.objectType,
          category: op.category,
          properties: {
            durability: op.durability,
            flammability: op.flammability,
            conductivity: op.conductivity,
            lootValue: op.lootValue,
            immovable: op.immovable,
          },
        });
      }
    }

    // --- 3. Drag / push for immovable objects ---

    if (ctx.inputState.pointerDown && nearestEntity) {
      const op = nearestEntity.objectProperties!;
      if (op.immovable && nearestEntity.physicsBody) {
        const body = ctx.bodyRegistry.get(
          nearestEntity.physicsBody.bodyId,
        );
        if (body) {
          // Compute force direction from object toward pointer
          const objX = nearestEntity.position!.x;
          const objY = nearestEntity.position!.y;
          const dx = ctx.inputState.pointerWorldX - objX;
          const dy = ctx.inputState.pointerWorldY - objY;
          const dist = Math.sqrt(dx * dx + dy * dy);

          if (dist > 1) {
            const nx = dx / dist;
            const ny = dy / dist;

            // Apply force via Matter.js body
            body.force.x += nx * DRAG_FORCE;
            body.force.y += ny * DRAG_FORCE;

            // Emit noise for future zombie AI
            safeEmit(ctx.eventBus, "noise-generated", {
              position: { x: objX, y: objY },
              radius: DRAG_NOISE_RADIUS,
              source: "drag",
            });
          }
        }
      }
    }

    // --- 4. Drop commands from UI ---

    while (pendingDrops.length > 0) {
      const dropCmd = pendingDrops.pop()!;

      // Resolve what to drop — validate definition BEFORE removing from
      // inventory so the item is never lost on undefined-def errors.
      let objectType: string | null = null;
      let resolvedSlotIndex: number | undefined;

      if (dropCmd.slotIndex !== undefined) {
        const slot = inv.slots[dropCmd.slotIndex];
        if (!slot) continue;
        // Pass the slot index directly — removeItem handles
        // continuation→primary resolution via backward search.
        objectType = slot.objectType;
        resolvedSlotIndex = dropCmd.slotIndex;
      } else if (dropCmd.objectType !== undefined) {
        objectType = dropCmd.objectType;
      }

      if (!objectType) continue;

      const def = getObjectDef(objectType);
      if (!def) {
        console.warn(
          `[InteractionSystem] Unknown object type for drop: ${objectType}`,
        );
        continue; // Safe: inventory not yet mutated
      }

      // NOW remove from inventory (after validation)
      if (resolvedSlotIndex !== undefined) {
        removeItem(inv, resolvedSlotIndex);
      } else if (!removeItemByType(inv, objectType)) {
        continue; // Item not found in inventory
      }

      // Compute drop position in front of player (based on aim direction)
      const aimDx = ctx.inputState.aimX - px;
      const aimDy = ctx.inputState.aimY - py;
      const aimDist = Math.sqrt(aimDx * aimDx + aimDy * aimDy);
      let dropX = px;
      let dropY = py + DROP_OFFSET;
      if (aimDist > 1) {
        dropX = px + (aimDx / aimDist) * DROP_OFFSET;
        dropY = py + (aimDy / aimDist) * DROP_OFFSET;
      }

      // Create world entity — if this fails, re-add to inventory.
      // This prevents item loss in a permadeath roguelike.
      try {
        const bodySize = def.immovable ? 32 : 16;
        const newBody = ctx.scene.matter.add.rectangle(
          dropX,
          dropY,
          bodySize,
          bodySize,
          {
            isStatic: false,
            friction: def.immovable ? 0.95 : 0.8,
            frictionAir: def.immovable ? 0.3 : 0.1,
            restitution: 0.2,
            mass: def.immovable ? def.physics.mass * 10 : def.physics.mass,
          },
        );
        newBody.inertia = Infinity;
        newBody.inverseInertia = 0;
        ctx.bodyRegistry.register(newBody);

        createObjectEntity(
          dropX,
          dropY,
          newBody.id,
          objectType,
          def.category,
          def.immovable,
          def.physics,
          def.lootValue,
        );
      } catch (err) {
        console.error(
          `[InteractionSystem] Failed to spawn dropped object ${objectType}:`,
          err,
        );
        // Re-add item to inventory to prevent loss
        const reAdded = addItem(inv, objectType);
        if (!reAdded) {
          console.error(
            `[InteractionSystem] CRITICAL: Failed to re-add ${objectType} to inventory after spawn failure — item lost!`,
          );
        }
        // Emit inventory-changed so UI stays in sync
        safeEmit(ctx.eventBus, "inventory-changed", {
          slots: buildEventSlots(inv),
          carryWeight: inv.carryWeight,
          maxCarryWeight: inv.maxCarryWeight,
        });
        continue;
      }

      // Emit events
      safeEmit(ctx.eventBus, "object-dropped", {
        objectType,
        position: { x: dropX, y: dropY },
      });
      safeEmit(ctx.eventBus, "inventory-changed", {
        slots: buildEventSlots(inv),
        carryWeight: inv.carryWeight,
        maxCarryWeight: inv.maxCarryWeight,
      });
    }
  };
}
