/**
 * Tunable constants for the wave spawner system.
 *
 * The wave configuration table defines per-night escalation:
 * zombie counts, pulse timing, approach directions, and stat scaling.
 * Night 4+ uses the terminal entry with progressive stat multipliers.
 *
 * NO React imports allowed — this is pure TypeScript.
 */

// ---------------------------------------------------------------------------
// Wave configuration per night
// ---------------------------------------------------------------------------

/** Configuration for a single night's zombie wave. */
export interface NightWaveConfig {
  /** Total zombie count range [min, max] for the entire night. */
  totalCount: { min: number; max: number };
  /** Number of approach directions (edge groups) active. */
  approachDirections: number;
  /** Number of spawning pulses the night is divided into. */
  pulseCount: number;
  /** Seconds of pause between pulses (barricade repair window). */
  pulsePause: number;
  /** Seconds between individual zombie spawns within a pulse. */
  spawnInterval: number;
  /** Stat multiplier applied to zombie speed, damage, and health. */
  statMultiplier: number;
}

/**
 * Per-night wave configurations, indexed by night number (1-based).
 * Nights beyond the array length use the last entry with scaling.
 */
const WAVE_TABLE: readonly NightWaveConfig[] = [
  // Night 1: 5-8 shamblers, single direction, gentle intro
  {
    totalCount: { min: 5, max: 8 },
    approachDirections: 1,
    pulseCount: 2,
    pulsePause: 15,
    spawnInterval: 0.8,
    statMultiplier: 1.0,
  },
  // Night 2: 12-18, dual direction, runners appear
  {
    totalCount: { min: 12, max: 18 },
    approachDirections: 2,
    pulseCount: 3,
    pulsePause: 12,
    spawnInterval: 0.6,
    statMultiplier: 1.0,
  },
  // Night 3: 25-35, all directions, brutes target weakest
  {
    totalCount: { min: 25, max: 35 },
    approachDirections: 4,
    pulseCount: 4,
    pulsePause: 10,
    spawnInterval: 0.4,
    statMultiplier: 1.0,
  },
  // Night 4+: 40-55, all directions, stat scaling begins
  {
    totalCount: { min: 40, max: 55 },
    approachDirections: 4,
    pulseCount: 5,
    pulsePause: 7,
    spawnInterval: 0.3,
    statMultiplier: 1.15,
  },
];

// ---------------------------------------------------------------------------
// Configuration lookup
// ---------------------------------------------------------------------------

/** Per-night stat multiplier growth for nights beyond 4. */
export const STAT_MULTIPLIER_GROWTH = 0.05;

/** Per-night total count multiplier for nights beyond 4. */
export const COUNT_SCALE_FACTOR = 1.1;

/**
 * Get the wave configuration for a given night number.
 *
 * Nights 1-4 use fixed entries. Night 5+ scales from the night-4
 * baseline with progressive stat and count multipliers.
 */
export function getWaveConfig(nightNumber: number): NightWaveConfig {
  if (!Number.isFinite(nightNumber) || nightNumber < 1) {
    console.warn(
      `[wave-system] getWaveConfig called with invalid nightNumber: ${nightNumber}. Defaulting to 1.`,
    );
    nightNumber = 1;
  }

  const idx = Math.min(nightNumber - 1, WAVE_TABLE.length - 1);
  const base = WAVE_TABLE[idx];

  // Nights within the table: use as-is (deep-clone totalCount)
  if (nightNumber <= WAVE_TABLE.length) {
    return { ...base, totalCount: { ...base.totalCount } };
  }

  // Nights beyond the table: scale from the terminal entry
  const overflow = nightNumber - WAVE_TABLE.length;
  const countScale = Math.pow(COUNT_SCALE_FACTOR, overflow);
  const statScale = base.statMultiplier + STAT_MULTIPLIER_GROWTH * overflow;

  return {
    ...base,
    totalCount: {
      min: Math.round(base.totalCount.min * countScale),
      max: Math.round(base.totalCount.max * countScale),
    },
    statMultiplier: statScale,
  };
}

// ---------------------------------------------------------------------------
// Additional wave system constants
// ---------------------------------------------------------------------------

export const WAVE_SYSTEM = {
  /**
   * Number of edges to group spawn zones by.
   * Edge zones are generated 3 per edge in order: north, south, west, east.
   */
  EDGES: 4,

  /** Zones per edge generated by spawn-zones.ts. */
  ZONES_PER_EDGE: 3,
} as const;
